#!/bin/bash
#This should run after the build is deployed.
echo "Installing perl modules..."

cd $OPENSHIFT_REPO_DIR/plibs/Archive-Zip-1.49/
perl Makefile.PL INSTALL_BASE=$OPENSHIFT_REPO_DIR/routes/app/reports/pmodules
make
make install

cd $OPENSHIFT_REPO_DIR/plibs/Data-Dumper-2.154/
perl Makefile.PL INSTALL_BASE=$OPENSHIFT_REPO_DIR/routes/app/reports/pmodules
make
make install

cd $OPENSHIFT_REPO_DIR/plibs/JSON-Parse-0.32/
perl Makefile.PL INSTALL_BASE=$OPENSHIFT_REPO_DIR/routes/app/reports/pmodules
make
make install

cd $OPENSHIFT_REPO_DIR/plibs/Spreadsheet-WriteExcel-2.40/
perl Makefile.PL INSTALL_BASE=$OPENSHIFT_REPO_DIR/routes/app/reports/pmodules
make
make install

echo "...Done!"