/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of Json3.xs. Do not edit this file, edit Json3.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Json3.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

/* TESTRANDOM should never be defined in the code released to
   CPAN. This is tested in "xt/testrandom-invalid.t". */

//#define TESTRANDOM

#ifdef TESTRANDOM
#include <setjmp.h>
#endif /* def TESTRANDOM */

/* Experimental. */

static SV * json_diagnostics;

/* All instances of JSON literals are pointed to the following. These
   are initialized in "BOOT" in "Json3.xs". */

static SV * json_true;
static SV * json_false;
static SV * json_null;

#include "unicode.h"
#include "unicode.c"
#include "json-common.c"
#define PERLING
#include "json-perl.c"
#undef PERLING
#define TOKENING
#include "json-perl.c"
#undef TOKENING
#include "json-perl.c"
#include "json-entry-points.c"
#ifdef TESTRANDOM
#include "json-random-test.c"
#endif /* def TESTRANDOM */
#include "json-whitespace.c"

typedef json_token_t * JSON__Tokenize;

#line 53 "Json3.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 195 "Json3.c"

XS_EUPXS(XS_JSON__Parse_parse_json); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_JSON__Parse_parse_json)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "json");
    {
	SV *	json = ST(0)
;
	SV *	RETVAL;
#line 62 "Json3.xs"
	RETVAL = parse (json);
#line 209 "Json3.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_JSON__Parse_assert_valid_json); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_JSON__Parse_assert_valid_json)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "json");
    {
	SV *	json = ST(0)
;
#line 69 "Json3.xs"
	validate (json);
#line 228 "Json3.c"
    }
    XSRETURN_EMPTY;
}

#ifdef TESTRANDOM
#define XSubPPtmpAAAA 1


XS_EUPXS(XS_JSON__Parse_random_json); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_JSON__Parse_random_json)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 75 "Json3.xs"
	RETVAL = random_json ();
#line 248 "Json3.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#endif /* def TESTRANDOM */

XS_EUPXS(XS_JSON__Tokenize_tokenize_json); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_JSON__Tokenize_tokenize_json)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "json");
    {
	SV *	json = ST(0)
;
	JSON__Tokenize	RETVAL;
#line 86 "Json3.xs"
	RETVAL = tokenize (json);
#line 268 "Json3.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "JSON::Tokenize", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_JSON__Tokenize_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_JSON__Tokenize_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "tokens");
    {
	json_token_t *	tokens;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    tokens = INT2PTR(json_token_t *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not a reference",
			"JSON::Tokenize::DESTROY",
			"tokens")
;
#line 93 "Json3.xs"
	tokenize_free (tokens);
#line 296 "Json3.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_JSON__Whitespace_strip_whitespace); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_JSON__Whitespace_strip_whitespace)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "tokens, json");
    {
	JSON__Tokenize	tokens;
	SV *	json = ST(1)
;
	SV *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "JSON::Tokenize")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    tokens = INT2PTR(JSON__Tokenize,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"JSON::Whitespace::strip_whitespace",
			"tokens", "JSON::Tokenize")
;
#line 101 "Json3.xs"
	RETVAL = strip_whitespace (tokens, json);
#line 325 "Json3.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_JSON__Parse); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_JSON__Parse)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("JSON::Parse::parse_json", XS_JSON__Parse_parse_json, file);
        newXS("JSON::Parse::assert_valid_json", XS_JSON__Parse_assert_valid_json, file);
#if XSubPPtmpAAAA
        newXS("JSON::Parse::random_json", XS_JSON__Parse_random_json, file);
#endif
        newXS("JSON::Tokenize::tokenize_json", XS_JSON__Tokenize_tokenize_json, file);
        newXS("JSON::Tokenize::DESTROY", XS_JSON__Tokenize_DESTROY, file);
        newXS("JSON::Whitespace::strip_whitespace", XS_JSON__Whitespace_strip_whitespace, file);

    /* Initialisation Section */

#line 48 "Json3.xs"
{
	json_true = get_sv ("JSON::Parse::true", GV_ADD);
	sv_setiv (json_true, 1);
	SvREADONLY_on (json_true);
	json_false = get_sv ("JSON::Parse::false", GV_ADD);
	sv_setiv (json_false, 0);
	SvREADONLY_on (json_false);
	json_null = get_sv ("JSON::Parse::null", GV_ADD);
	SvREADONLY_on (json_null);
}

#if XSubPPtmpAAAA
#endif
#line 377 "Json3.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

